train:
  _target_: torch.utils.data.ConcatDataset # we can concat datasets if we want to
  datasets:
    - _target_: src.datasets.SourceSeparationDataset
      part: "train"
      video: False
      instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.SourceSeparationDataset
  part: "val"
  video: False
  instance_transforms: ${transforms.instance_transforms.inference}
test:
  _target_: src.datasets.SourceSeparationDataset
  part: "val"
  video: False
  instance_transforms: ${transforms.instance_transforms.inference}
