train:
  _target_: src.datasets.SourceSeparationDataset
  part: "train"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.SourceSeparationDataset
  part: "val"
  instance_transforms: ${transforms.instance_transforms.inference}
