_target_: src.model.RTFSModel
audio_channels: 256
video_channels: 512
encoder_params:
        hop_length: 128
        features: 256

separation_params:
  rtfs_repeats: 4
  rnn_type_str: SRU #SRU GRU supported

  # audio net part
  audio_block_params:
    kernel_size: 4
    hid_channels: 64
    stride: 2
    downsample_layers_count: 2
    is_conv_2d: true
  dual_path_rnn_params:
    in_channels: 64
    hidden_channels: 32
    num_layers: 4
    kernel_size: 8
    stride: 1
    bidirectional: True
  audio_attention_params:
    in_channels: 64
    features_dim: 64
    hidden_channels: 4
    num_heads: 4

  # video net part
  video_block_params:
    kernel_size: 3
    hid_channels: 64
    stride: 2
    downsample_layers_count: 2
    is_conv_2d: false
  video_attention_params:
    in_channels: 64
    kernel_size: 3
    num_heads: 8
    dropout: 0.1
  # CAF params
  CAF_params:
    num_heads: 8

decoder_parms:
        hop_length: ${model.encoder_params.hop_length}
        features: ${model.encoder_params.features}
        length: 32000 #wav length
