defaults:
  - model: rtfs_model
  - metrics: empty
  - datasets: rtfs_eval
  - dataloader: rtfs
  - transforms: rtfs
  - _self_
inferencer:
  device_tensors: ["mix", "video_embed"]
  device: auto
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/pretrain.pth" # path to the pretrained model
