defaults:
  - model: rtfs_model
  - writer: wandb
  - metrics: base_metrics
  - datasets: example
  - dataloader: example
  - transforms: example
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-5
  weight_decay: 1e-1
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 1e-3
  pct_start: 1e-3
  div_factor: 1
  total_steps: 5000
loss_function:
  _target_: src.loss.SiSNRLoss
trainer:
  log_step: 50
  n_epochs: 100
  epoch_len: 500
  device_tensors: ["mix", "target", "video_embed"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max SiSNRI" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
  max_grad_norm: 5
