defaults:
  - model: rtfs_model
  - writer: wandb
  - metrics: rtfs_metrics
  - datasets: rtfs
  - dataloader: rtfs
  - transforms: example
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 1e-1
lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: 'min'
  factor: 0.5
  patience: 5
  verbose: True
  min_lr: 1e-6
loss_function:
  _target_: src.loss.SimpleSiSNRLoss
trainer:
  log_step: 50
  n_epochs: 20
  epoch_len: 666
  device_tensors: ["mix", "target", "video_embed"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "max TEST_SiSNRI" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved_exp_2"
  seed: 42
  max_grad_norm: 5
